-- Supabase/PostgreSQL schema, constraints, relationships, RLS, views, and realtime tables
create extension if not exists "uuid-ossp";
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, role text not null default 'user' check (role in ('user','admin')), created_at timestamptz default now());
create table if not exists products (id uuid primary key default uuid_generate_v4(), name text not null, price numeric(10,2) not null check (price >= 0), created_at timestamptz default now());
create table if not exists student_marks (id uuid primary key default uuid_generate_v4(), user_id uuid not null references profiles(id) on delete cascade, subject text not null, marks int not null check (marks between 0 and 100));
create table if not exists messages (id bigint generated by default as identity primary key, user_id uuid references profiles(id) on delete set null, body text not null, created_at timestamptz default now());
create or replace view student_summary as select user_id, avg(marks) as average_marks, count(*) as subject_count from student_marks group by user_id;
create index if not exists idx_marks_user on student_marks(user_id);

alter table profiles enable row level security;
alter table student_marks enable row level security;
alter table messages enable row level security;
create policy "users can read own profile" on profiles for select using (auth.uid()=id);
create policy "users can update own profile" on profiles for update using (auth.uid()=id);
create policy "users can manage own marks" on student_marks for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "authenticated users can read messages" on messages for select to authenticated using (true);
create policy "authenticated users can send messages" on messages for insert to authenticated with check (auth.uid()=user_id);

-- Enable Realtime for chat/record updates in the Supabase dashboard or with:
-- alter publication supabase_realtime add table messages;

-- CRUD examples in SQL Editor:
-- insert into products(name,price) values ('Notebook',10);
-- select * from products order by created_at desc;
-- update products set price=12 where name='Notebook';
-- delete from products where name='Notebook';
